/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    team: Team;
    publications: Publication;
    'in-focus': InFocus;
    'magazine-issues': MagazineIssue;
    'podcast-episodes': PodcastEpisode;
    documentaries: Documentary;
    events: Event;
    'focus-areas': FocusArea;
    'membership-tiers': MembershipTier;
    faqs: Faq;
    partners: Partner;
    'open-roles': OpenRole;
    gallery: Gallery;
    members: Member;
    submissions: Submission;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    team: TeamSelect<false> | TeamSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'in-focus': InFocusSelect<false> | InFocusSelect<true>;
    'magazine-issues': MagazineIssuesSelect<false> | MagazineIssuesSelect<true>;
    'podcast-episodes': PodcastEpisodesSelect<false> | PodcastEpisodesSelect<true>;
    documentaries: DocumentariesSelect<false> | DocumentariesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'focus-areas': FocusAreasSelect<false> | FocusAreasSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'open-roles': OpenRolesSelect<false> | OpenRolesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'impact-stats': ImpactStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'impact-stats': ImpactStatsSelect<false> | ImpactStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  department:
    | 'board'
    | 'exec'
    | 'research-policy'
    | 'partnerships'
    | 'stakeholder'
    | 'hr-ops'
    | 'legal'
    | 'media-production';
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cvFile?: (number | null) | Media;
  linkedin?: string | null;
  email?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  format: 'brief' | 'report' | 'working-paper' | 'white-paper';
  themes?: (number | FocusArea)[] | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: (number | Team)[] | null;
  cover?: (number | null) | Media;
  /**
   * PDF file download for the publication.
   */
  attachment?: (number | null) | Media;
  publishDate: string;
  /**
   * If checked, this publication will require a paid membership or individual purchase to download/read.
   */
  gated?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus-areas".
 */
export interface FocusArea {
  id: number;
  name: string;
  description?: string | null;
  sdgTags?:
    | (
        | 'sdg1'
        | 'sdg3'
        | 'sdg4'
        | 'sdg5'
        | 'sdg6'
        | 'sdg7'
        | 'sdg8'
        | 'sdg9'
        | 'sdg10'
        | 'sdg12'
        | 'sdg13'
        | 'sdg16'
        | 'sdg17'
      )[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-focus".
 */
export interface InFocus {
  id: number;
  title: string;
  image: number | Media;
  caption?: string | null;
  relatedPublication?: (number | null) | Publication;
  themes?: (number | FocusArea)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues".
 */
export interface MagazineIssue {
  id: number;
  issueNo: string;
  title: string;
  cover: number | Media;
  theme?: (number | null) | FocusArea;
  /**
   * Excerpt available to everyone, including free tier members.
   */
  freeExcerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full body content of the issue, accessible only by paid tiers.
   */
  gatedBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full PDF version of the issue (gated).
   */
  gatedPDF?: (number | null) | Media;
  publishDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes".
 */
export interface PodcastEpisode {
  id: number;
  number: string;
  title: string;
  guests?: (number | Team)[] | null;
  /**
   * Iframe embed code (e.g., from Audiomack, Spotify, or YouTube).
   */
  audioEmbed?: string | null;
  platformLinks?: {
    spotify?: string | null;
    apple?: string | null;
    youtube?: string | null;
    audiomack?: string | null;
    rss?: string | null;
  };
  summary: string;
  /**
   * Duration of the episode (e.g., 42 min).
   */
  duration?: string | null;
  /**
   * Cover image / thumbnail for the podcast episode.
   */
  cover?: (number | null) | Media;
  keyTakeaways?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full transcript for SEO and accessibility.
   */
  transcript?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentaries".
 */
export interface Documentary {
  id: number;
  title: string;
  /**
   * YouTube embed URL or iframe code.
   */
  videoEmbed: string;
  about: string;
  /**
   * e.g., 14 mins
   */
  length?: string | null;
  year?: string | null;
  relatedResearch?: (number | Publication)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  type: 'conference' | 'seminar' | 'forum' | 'webinar' | 'lecture' | 'roundtable' | 'launch';
  date: string;
  /**
   * Venue name (e.g. Bauchi Conference Hall) or online platform (e.g. Zoom).
   */
  location?: string | null;
  format: 'in-person' | 'online' | 'hybrid';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * External link for ticket purchases or registrations.
   */
  registrationURL?: string | null;
  /**
   * Cover image / thumbnail for the event.
   */
  image?: (number | null) | Media;
  /**
   * Post-event video recording link (YouTube, Vimeo, etc.).
   */
  recording?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: number;
  name: string;
  /**
   * Who this tier is targetted at, e.g. Students, professionals.
   */
  audience?: string | null;
  /**
   * Annual price in Nigerian Naira (₦). Enter 0 for free.
   */
  priceNGN: number;
  /**
   * Annual price in USD ($) for the diaspora path. Enter 0 for free.
   */
  priceUSD: number;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-roles".
 */
export interface OpenRole {
  id: number;
  title: string;
  department?: string | null;
  location?: string | null;
  type: 'full-time' | 'part-time' | 'contract' | 'internship';
  deadline?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  applyURL?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  type: 'picture' | 'video';
  /**
   * The image to display (or video cover thumbnail). If empty, a default placeholder is used.
   */
  image?: (number | null) | Media;
  /**
   * YouTube or Vimeo video URL (required if type is video).
   */
  videoUrl?: string | null;
  publishDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  tier?: (number | null) | MembershipTier;
  paidUntil?: string | null;
  paystackRef?: string | null;
  /**
   * If checked, this member has full administrative access to edit content.
   */
  isAdmin?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  formType: 'newsletter' | 'consultation' | 'contact' | 'cv-submission';
  name?: string | null;
  email: string;
  organisation?: string | null;
  message?: string | null;
  cvFile?: (number | null) | Media;
  engagementType?: ('research' | 'training' | 'advisory' | 'evaluation' | 'other') | null;
  deliverables?: string | null;
  timeline?: string | null;
  budget?: string | null;
  timestamp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'in-focus';
        value: number | InFocus;
      } | null)
    | ({
        relationTo: 'magazine-issues';
        value: number | MagazineIssue;
      } | null)
    | ({
        relationTo: 'podcast-episodes';
        value: number | PodcastEpisode;
      } | null)
    | ({
        relationTo: 'documentaries';
        value: number | Documentary;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'focus-areas';
        value: number | FocusArea;
      } | null)
    | ({
        relationTo: 'membership-tiers';
        value: number | MembershipTier;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'open-roles';
        value: number | OpenRole;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  department?: T;
  photo?: T;
  bio?: T;
  cvFile?: T;
  linkedin?: T;
  email?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  format?: T;
  themes?: T;
  excerpt?: T;
  body?: T;
  authors?: T;
  cover?: T;
  attachment?: T;
  publishDate?: T;
  gated?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-focus_select".
 */
export interface InFocusSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  relatedPublication?: T;
  themes?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues_select".
 */
export interface MagazineIssuesSelect<T extends boolean = true> {
  issueNo?: T;
  title?: T;
  cover?: T;
  theme?: T;
  freeExcerpt?: T;
  gatedBody?: T;
  gatedPDF?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes_select".
 */
export interface PodcastEpisodesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  guests?: T;
  audioEmbed?: T;
  platformLinks?:
    | T
    | {
        spotify?: T;
        apple?: T;
        youtube?: T;
        audiomack?: T;
        rss?: T;
      };
  summary?: T;
  duration?: T;
  cover?: T;
  keyTakeaways?:
    | T
    | {
        point?: T;
        id?: T;
      };
  transcript?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentaries_select".
 */
export interface DocumentariesSelect<T extends boolean = true> {
  title?: T;
  videoEmbed?: T;
  about?: T;
  length?: T;
  year?: T;
  relatedResearch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  location?: T;
  format?: T;
  description?: T;
  registrationURL?: T;
  image?: T;
  recording?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus-areas_select".
 */
export interface FocusAreasSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  sdgTags?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  name?: T;
  audience?: T;
  priceNGN?: T;
  priceUSD?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-roles_select".
 */
export interface OpenRolesSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  deadline?: T;
  body?: T;
  applyURL?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  type?: T;
  image?: T;
  videoUrl?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  tier?: T;
  paidUntil?: T;
  paystackRef?: T;
  isAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  organisation?: T;
  message?: T;
  cvFile?: T;
  engagementType?: T;
  deliverables?: T;
  timeline?: T;
  budget?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  title: string;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Corporate affairs commission (CAC) registration number.
   */
  registrationNumber?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletterMicrocopy?: string | null;
  socials?: {
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats".
 */
export interface ImpactStat {
  id: number;
  conversations: string;
  publications: string;
  partners: string;
  reached: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  logo?: T;
  registrationNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  newsletterMicrocopy?: T;
  socials?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  conversations?: T;
  publications?: T;
  partners?: T;
  reached?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}